export const DEMO_MENU_ITEMS = [
  {
    id: "hot-1",
    name: "Шаурма классическая",
    description: "Сочная курица, свежие овощи, фирменный соус в хрустящем лаваше",
    price: 250,
    category: "Горячее",
    imageUrl: "/assets/images/hot-dishes.png",
    weight: 380,
    calories: 520,
    proteins: 28,
    fats: 18,
    carbs: 55,
    ingredients: "Лаваш, куриное филе, помидоры, огурцы, маринованный лук, белокочанная капуста, фирменный соус (майонез, чеснок, зелень), специи",
    allergens: "Глютен, яйца",
  },
  {
    id: "hot-2",
    name: "Картошка фри",
    description: "Золотистая и хрустящая, с солью",
    price: 120,
    category: "Горячее",
    imageUrl: "/assets/images/hot-dishes.png",
    weight: 200,
    calories: 340,
    proteins: 4,
    fats: 17,
    carbs: 44,
    ingredients: "Картофель, растительное масло, соль",
    allergens: "Нет",
  },
  {
    id: "hot-3",
    name: "Куриные наггетсы",
    description: "Нежное куриное филе в хрустящей панировке, 6 шт",
    price: 180,
    category: "Горячее",
    imageUrl: "/assets/images/hot-dishes.png",
    weight: 180,
    calories: 390,
    proteins: 22,
    fats: 21,
    carbs: 28,
    ingredients: "Куриное филе, панировочные сухари, яйцо, соль, перец, специи, растительное масло",
    allergens: "Глютен, яйца",
  },
  {
    id: "burger-1",
    name: "Бургер с говядиной",
    description: "Котлета из 100% говядины, сыр чеддер, салат, томаты, соус",
    price: 290,
    category: "Бургеры",
    imageUrl: "/assets/images/burger.png",
    weight: 320,
    calories: 610,
    proteins: 32,
    fats: 30,
    carbs: 52,
    ingredients: "Булочка с кунжутом, говяжья котлета (100% говядина), сыр чеддер, лист салата, томаты, маринованные огурцы, лук, соус бургерный",
    allergens: "Глютен, молоко, яйца, горчица",
  },
  {
    id: "burger-2",
    name: "Чизбургер",
    description: "Классический чизбургер с говяжьей котлетой и расплавленным сыром",
    price: 270,
    category: "Бургеры",
    imageUrl: "/assets/images/burger.png",
    weight: 280,
    calories: 560,
    proteins: 28,
    fats: 26,
    carbs: 48,
    ingredients: "Булочка с кунжутом, говяжья котлета, сыр чеддер, маринованные огурцы, лук, кетчуп, горчица",
    allergens: "Глютен, молоко, яйца, горчица",
  },
  {
    id: "burger-3",
    name: "Вегетарианский бургер",
    description: "Растительная котлета, свежие овощи, веганский соус",
    price: 240,
    category: "Бургеры",
    imageUrl: "/assets/images/burger.png",
    weight: 290,
    calories: 420,
    proteins: 14,
    fats: 16,
    carbs: 55,
    ingredients: "Булочка с кунжутом, растительная котлета (нут, горох, морковь), лист салата, томаты, авокадо, веганский соус",
    allergens: "Глютен, соя",
  },
  {
    id: "drink-1",
    name: "Кола",
    description: "Охлаждающий газированный напиток",
    price: 80,
    category: "Напитки",
    imageUrl: "/assets/images/drinks.png",
    weight: 500,
    calories: 210,
    proteins: 0,
    fats: 0,
    carbs: 53,
    ingredients: "Газированная вода, сахар, карамельный колер, ортофосфорная кислота, натуральные ароматизаторы, кофеин",
    allergens: "Нет",
  },
  {
    id: "drink-2",
    name: "Сок",
    description: "Яблочный или апельсиновый, натуральный",
    price: 90,
    category: "Напитки",
    imageUrl: "/assets/images/drinks.png",
    weight: 500,
    calories: 120,
    proteins: 1,
    fats: 0,
    carbs: 28,
    ingredients: "100% натуральный сок без добавления сахара и консервантов",
    allergens: "Нет",
  },
  {
    id: "drink-3",
    name: "Вода",
    description: "Негазированная минеральная вода",
    price: 50,
    category: "Напитки",
    imageUrl: "/assets/images/drinks.png",
    weight: 500,
    calories: 0,
    proteins: 0,
    fats: 0,
    carbs: 0,
    ingredients: "Природная минеральная вода",
    allergens: "Нет",
  },
  {
    id: "drink-4",
    name: "Кофе",
    description: "Свежесваренный американо или капучино",
    price: 110,
    category: "Напитки",
    imageUrl: "/assets/images/drinks.png",
    weight: 300,
    calories: 45,
    proteins: 2,
    fats: 2,
    carbs: 5,
    ingredients: "Эспрессо (молотый кофе, вода). Капучино: эспрессо, молоко",
    allergens: "Молоко (для капучино)",
  },
  {
    id: "dessert-1",
    name: "Мороженое",
    description: "Ванильный рожок в хрустящей вафле",
    price: 90,
    category: "Десерты",
    imageUrl: "/assets/images/desserts.png",
    weight: 120,
    calories: 230,
    proteins: 4,
    fats: 10,
    carbs: 32,
    ingredients: "Молоко, сливки, сахар, ванильный экстракт, вафельный рожок (пшеничная мука, сахар, яйца)",
    allergens: "Молоко, глютен, яйца",
  },
  {
    id: "dessert-2",
    name: "Пирожок",
    description: "Горячий пирожок с вишневой начинкой",
    price: 70,
    category: "Десерты",
    imageUrl: "/assets/images/desserts.png",
    weight: 130,
    calories: 290,
    proteins: 5,
    fats: 12,
    carbs: 42,
    ingredients: "Тесто (пшеничная мука, яйца, масло, соль, сахар, дрожжи), начинка вишнёвая (вишня, сахар, крахмал)",
    allergens: "Глютен, яйца, молоко",
  },
];
